"""add deviation table

Revision ID: 0920635bb8dc
Revises: e3be40fcc76f
Create Date: 2026-09-10 16:44:25.431980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0920635bb8dc'
down_revision: Union[str, Sequence[str], None] = 'e3be40fcc76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviation',
    sa.Column('dc_id', sa.UUID(), nullable=False),
    sa.Column('deviation_type', sa.String(length=20), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=False),
    sa.Column('difference_qty', sa.Integer(), nullable=False),
    sa.Column('mail_status', sa.String(length=20), nullable=False),
    sa.Column('vendor_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['delivery_challan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deviation')
    # ### end Alembic commands ###
