"""add deviation resolution fields

Revision ID: 543f48b245a4
Revises: b54685e58a6c
Create Date: 2026-09-16 13:51:42.493064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543f48b245a4'
down_revision: Union[str, Sequence[str], None] = 'b54685e58a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviation', sa.Column('resolved_by', sa.String(length=100), nullable=True))
    op.add_column('deviation', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deviation', 'resolved_at')
    op.drop_column('deviation', 'resolved_by')
    # ### end Alembic commands ###
