"""add sap_movement table

Revision ID: 74e7bde574a7
Revises: 80de06b3b97e
Create Date: 2026-09-11 16:14:48.203611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e7bde574a7'
down_revision: Union[str, Sequence[str], None] = '80de06b3b97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_movement',
    sa.Column('dc_id', sa.UUID(), nullable=False),
    sa.Column('material_document_no', sa.String(length=50), nullable=False),
    sa.Column('movement_type', sa.String(length=10), nullable=False),
    sa.Column('posting_date', sa.String(length=20), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['delivery_challan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_movement_material_document_no'), 'sap_movement', ['material_document_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_movement_material_document_no'), table_name='sap_movement')
    op.drop_table('sap_movement')
    # ### end Alembic commands ###
