"""add receiving category and physical verification fields

Revision ID: 7c6d6e6c841d
Revises: b9b6cac78160
Create Date: 2026-09-17 20:05:49.547755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6d6e6c841d'
down_revision: Union[str, Sequence[str], None] = 'b9b6cac78160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('receiving_category', sa.String(length=20), nullable=True))
    op.add_column('delivery_challan', sa.Column('receiving_category_set_by', sa.String(length=100), nullable=True))
    op.add_column('delivery_challan', sa.Column('receiving_category_set_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_challan', sa.Column('physical_verification_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('delivery_challan', sa.Column('physical_verified_by', sa.String(length=100), nullable=True))
    op.add_column('delivery_challan', sa.Column('physical_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_challan', 'physical_verified_at')
    op.drop_column('delivery_challan', 'physical_verified_by')
    op.drop_column('delivery_challan', 'physical_verification_status')
    op.drop_column('delivery_challan', 'receiving_category_set_at')
    op.drop_column('delivery_challan', 'receiving_category_set_by')
    op.drop_column('delivery_challan', 'receiving_category')
    # ### end Alembic commands ###
