"""add vendor email field

Revision ID: 80de06b3b97e
Revises: 0920635bb8dc
Create Date: 2026-09-10 17:35:34.311253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80de06b3b97e'
down_revision: Union[str, Sequence[str], None] = '0920635bb8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'email')
    # ### end Alembic commands ###
