"""add po_quantity and actual received quantities

Revision ID: a9c73200bc98
Revises: 74e7bde574a7
Create Date: 2026-09-11 18:03:01.185125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c73200bc98'
down_revision: Union[str, Sequence[str], None] = '74e7bde574a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('actual_front_case', sa.Integer(), nullable=True))
    op.add_column('delivery_challan', sa.Column('actual_back_case', sa.Integer(), nullable=True))
    op.add_column('dispatch', sa.Column('po_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch', 'po_quantity')
    op.drop_column('delivery_challan', 'actual_back_case')
    op.drop_column('delivery_challan', 'actual_front_case')
    # ### end Alembic commands ###
