"""add ppc_collection table

Revision ID: b3760abed17a
Revises: 7c6d6e6c841d
Create Date: 2026-09-18 17:28:13.778192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3760abed17a'
down_revision: Union[str, Sequence[str], None] = '7c6d6e6c841d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppc_collection',
    sa.Column('dc_id', sa.UUID(), nullable=False),
    sa.Column('tray_no', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('collected_by', sa.String(length=100), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['delivery_challan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ppc_collection')
    # ### end Alembic commands ###
