"""add qc acknowledgement fields

Revision ID: b54685e58a6c
Revises: a9c73200bc98
Create Date: 2026-09-15 13:52:54.363685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54685e58a6c'
down_revision: Union[str, Sequence[str], None] = 'a9c73200bc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('qc_ack_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('delivery_challan', sa.Column('qc_acknowledged_by', sa.String(length=100), nullable=True))
    op.add_column('delivery_challan', sa.Column('qc_acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_challan', sa.Column('stock_level', sa.String(length=20), nullable=False, server_default='level_2'))
    op.add_column('delivery_challan', sa.Column('ud_post_status', sa.String(length=20), nullable=False, server_default='not_posted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_challan', 'ud_post_status')
    op.drop_column('delivery_challan', 'stock_level')
    op.drop_column('delivery_challan', 'qc_acknowledged_at')
    op.drop_column('delivery_challan', 'qc_acknowledged_by')
    op.drop_column('delivery_challan', 'qc_ack_status')
    # ### end Alembic commands ###
