"""add gate entry and subcon receiving fields

Revision ID: b9b6cac78160
Revises: 543f48b245a4
Create Date: 2026-09-17 12:55:20.032558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b6cac78160'
down_revision: Union[str, Sequence[str], None] = '543f48b245a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('gate_entry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_challan', sa.Column('gate_entry_by', sa.String(length=100), nullable=True))
    op.add_column('delivery_challan', sa.Column('subcon_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_challan', sa.Column('subcon_received_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_challan', 'subcon_received_by')
    op.drop_column('delivery_challan', 'subcon_received_at')
    op.drop_column('delivery_challan', 'gate_entry_by')
    op.drop_column('delivery_challan', 'gate_entry_at')
    # ### end Alembic commands ###
