"""add zqmtl1_processing table

Revision ID: dc8502a908fc
Revises: ea11feb9ca0f
Create Date: 2026-09-21 12:23:37.719745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8502a908fc'
down_revision: Union[str, Sequence[str], None] = 'ea11feb9ca0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zqmtl1_processing',
    sa.Column('dc_id', sa.UUID(), nullable=False),
    sa.Column('zqmtl1_status', sa.String(length=20), nullable=False),
    sa.Column('sap_status', sa.String(length=20), nullable=False),
    sa.Column('processed_by', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['delivery_challan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zqmtl1_processing')
    # ### end Alembic commands ###
