"""add storage_assignment table

Revision ID: e97ddc14e4cc
Revises: dc8502a908fc
Create Date: 2026-09-21 20:01:35.252953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97ddc14e4cc'
down_revision: Union[str, Sequence[str], None] = 'dc8502a908fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_assignment',
    sa.Column('dc_id', sa.UUID(), nullable=False),
    sa.Column('rack', sa.String(length=50), nullable=False),
    sa.Column('row', sa.String(length=50), nullable=False),
    sa.Column('bin', sa.String(length=50), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=False),
    sa.Column('stored_by', sa.String(length=100), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['delivery_challan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_assignment')
    # ### end Alembic commands ###
