"""add qa_inspection table

Revision ID: ea11feb9ca0f
Revises: b3760abed17a
Create Date: 2026-09-18 21:01:57.124125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea11feb9ca0f'
down_revision: Union[str, Sequence[str], None] = 'b3760abed17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_inspection',
    sa.Column('dc_id', sa.UUID(), nullable=False),
    sa.Column('inspection_status', sa.String(length=20), nullable=False),
    sa.Column('qa_user', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['delivery_challan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_inspection')
    # ### end Alembic commands ###
